"""Introspect the public SDK surface into self-contained Markdown.

``gaia sdk`` is an end-user CLI command, so the reference is generated by
plain :mod:`inspect` over the public API — **no** mkdocs / sphinx / griffe
runtime dependency. Content parallels what mkdocstrings renders for the
Pages site (names, signatures, Google-style docstrings), and applies the
same privacy filter as ``mkdocs.yml`` (``filters: ["!^_"]`` — drop any
``_``-prefixed member).

Two modules form the surface:

* :mod:`gaia.engine.lang` — the DSL verbs, relations, scaffolds,
  composition, typed terms, formula ops, and distribution factories.
* :mod:`gaia.engine.bayes` — ``model`` / ``compare`` plus the Bayes
  runtime records.

The generator pulls each module's ``__all__``, filters privates, and
renders one Markdown section per symbol with its signature and docstring.
"""

from __future__ import annotations

import importlib
import inspect
from dataclasses import dataclass
from types import ModuleType

# The two public surfaces the SDK reference documents, in render order.
SDK_MODULES: tuple[str, ...] = ("gaia.engine.lang", "gaia.engine.bayes")


@dataclass(frozen=True)
class SymbolDoc:
    """One documented public symbol."""

    name: str
    kind: str  # "function" / "class" / "other"
    signature: str
    docstring: str


@dataclass(frozen=True)
class ModuleDoc:
    """All documented public symbols for one module."""

    module: str
    summary: str
    symbols: tuple[SymbolDoc, ...]


def _is_public(name: str) -> bool:
    """Mirror the mkdocstrings ``!^_`` filter: drop ``_``-prefixed names."""
    return not name.startswith("_")


def _public_names(module: ModuleType) -> list[str]:
    """Return the module's public ``__all__`` names (privates filtered)."""
    declared = getattr(module, "__all__", None)
    if isinstance(declared, (list, tuple)):
        names = [n for n in declared if isinstance(n, str) and _is_public(n)]
    else:  # pragma: no cover - both SDK modules declare __all__
        names = [n for n in dir(module) if _is_public(n)]
    return sorted(names)


def _symbol_kind(obj: object) -> str:
    if inspect.isclass(obj):
        return "class"
    if inspect.isfunction(obj) or inspect.isbuiltin(obj) or callable(obj):
        return "function"
    return "other"


def _signature_for(name: str, obj: object) -> str:
    """Render a best-effort ``name(signature)`` string.

    Falls back to a bare ``name`` when the object exposes no introspectable
    signature (e.g. a non-callable runtime constant).
    """
    if not callable(obj):
        return name
    try:
        sig = inspect.signature(obj)
    except (TypeError, ValueError):
        return name
    return f"{name}{sig}"


def _clean_docstring(obj: object) -> str:
    """Return the dedented docstring, or a placeholder when absent."""
    doc = inspect.getdoc(obj)
    if not doc:
        return "_No docstring._"
    return doc.strip()


def introspect_module(module_name: str) -> ModuleDoc:
    """Introspect one SDK module into a :class:`ModuleDoc`."""
    module = importlib.import_module(module_name)
    summary = _clean_docstring(module).splitlines()[0] if inspect.getdoc(module) else ""
    symbols: list[SymbolDoc] = []
    for name in _public_names(module):
        obj = getattr(module, name)
        symbols.append(
            SymbolDoc(
                name=name,
                kind=_symbol_kind(obj),
                signature=_signature_for(name, obj),
                docstring=_clean_docstring(obj),
            )
        )
    return ModuleDoc(module=module_name, summary=summary, symbols=tuple(symbols))


def introspect_sdk() -> tuple[ModuleDoc, ...]:
    """Introspect every SDK module in :data:`SDK_MODULES`."""
    return tuple(introspect_module(name) for name in SDK_MODULES)


def render_module_markdown(doc: ModuleDoc) -> str:
    """Render one module's symbols as a self-contained Markdown page."""
    lines: list[str] = [f"# `{doc.module}`", ""]
    if doc.summary:
        lines.extend([doc.summary, ""])
    lines.append(
        f"Public API surface ({len(doc.symbols)} symbols), introspected from "
        f"`{doc.module}.__all__`. Private (`_`-prefixed) members are filtered, "
        "matching the Pages-site mkdocstrings config."
    )
    lines.append("")
    for sym in doc.symbols:
        lines.append(f"## `{sym.name}`")
        lines.append("")
        lines.append(f"_{sym.kind}_")
        lines.append("")
        lines.append("```python")
        lines.append(sym.signature)
        lines.append("```")
        lines.append("")
        lines.append(sym.docstring)
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_index_markdown(docs: tuple[ModuleDoc, ...]) -> str:
    """Render the SDK reference landing page linking each module page."""
    lines: list[str] = [
        "# Gaia SDK reference",
        "",
        "Self-contained API reference for authoring the Gaia DSL directly via "
        "the Python SDK — the **primary** authoring path. Generated by "
        "introspecting the public API surface (no mkdocs/sphinx needed).",
        "",
        "Start with **`CHEATSHEET.md`** (one page, every verb/term/distribution "
        "with a copy-pasteable example), then dive into the per-module reference:",
        "",
    ]
    for doc in docs:
        page = doc.module.replace(".", "_") + ".md"
        lines.append(f"- [`{doc.module}`]({page}) — {len(doc.symbols)} public symbols")
    lines.append("")
    lines.append(
        "Author your DSL directly in `src/<pkg>/__init__.py` (and your own "
        "modules); the `gaia author` CLI is an optional convenience that writes "
        "into the composed `authored/` submodule. See "
        "`docs/for-users/authoring-workflow.md` for the full model."
    )
    lines.append("")
    return "\n".join(lines)


def module_page_name(module_name: str) -> str:
    """Return the on-disk Markdown filename for a module's reference page."""
    return module_name.replace(".", "_") + ".md"


__all__ = [
    "SDK_MODULES",
    "ModuleDoc",
    "SymbolDoc",
    "introspect_module",
    "introspect_sdk",
    "module_page_name",
    "render_index_markdown",
    "render_module_markdown",
]
